/**
 * What each board looks like. The API decides what a role may do; this file
 * only decides how the columns are laid out and which views are offered.
 *
 * Column types: text, longtext, status, dept, person, people, date, timeline,
 * money, num, hours, points, pct, ref, tags, sla, rating, bool.
 */
const W = { name: 300, status: 150, person: 150, date: 110, timeline: 190, num: 90, money: 110, points: 70, text: 160 };

export const BOARDS = {
  leads: {
    title: 'Lead inbox',
    blurb: 'Every inbound and outbound enquiry before it becomes a qualified opportunity.',
    newFields: ['name','company','stage','source','owner_id','value'],
    views: ['table', 'kanban'], groupBy: 'stage', kanbanBy: 'stage', cardColor: 'source',
    columns: [
      { id: 'name', label: 'Lead', type: 'text', width: W.name },
      { id: 'company', label: 'Company', type: 'text', width: W.text },
      { id: 'stage', label: 'Stage', type: 'status', options: 'leadStage', width: W.status },
      { id: 'source', label: 'Source', type: 'status', options: 'source', width: W.status },
      { id: 'service', label: 'Interested in', type: 'status', options: 'service', width: W.status },
      { id: 'owner_id', label: 'Owner', type: 'person', width: W.person },
      { id: 'value', label: 'Est. value', type: 'money', width: W.money },
      { id: 'received_on', label: 'Received', type: 'date', width: W.date },
      { id: 'next_step', label: 'Next step', type: 'text', width: 220 },
    ],
  },
  deals: {
    title: 'Deal pipeline',
    blurb: 'Qualified opportunities from scoping through to signature. Drag a card to move the stage.',
    newFields: ['name','client_id','stage','value','probability','owner_id','close_date'],
    views: ['table', 'kanban', 'chart'], groupBy: 'stage', kanbanBy: 'stage', cardColor: 'service',
    columns: [
      { id: 'name', label: 'Deal', type: 'text', width: W.name },
      { id: 'client_id', label: 'Account', type: 'ref', ref: 'clients', width: W.text },
      { id: 'stage', label: 'Stage', type: 'status', options: 'dealStage', width: W.status },
      { id: 'service', label: 'Scope', type: 'status', options: 'service', width: W.status },
      { id: 'value', label: 'Contract value', type: 'money', width: 130 },
      { id: 'probability', label: 'Confidence', type: 'pct', width: W.status },
      { id: 'owner_id', label: 'Owner', type: 'person', width: W.person },
      { id: 'close_date', label: 'Expected close', type: 'date', width: 130 },
      { id: 'source', label: 'Source', type: 'status', options: 'source', width: W.status },
    ],
  },
  clients: {
    title: 'Accounts',
    blurb: 'Who Nuuke builds for, who owns the relationship, and how healthy it is.',
    newFields: ['name','industry','status','health','account_manager_id','region'],
    views: ['table', 'kanban'], groupBy: 'status', kanbanBy: 'health', cardColor: 'health',
    columns: [
      { id: 'name', label: 'Account', type: 'text', width: W.name },
      { id: 'industry', label: 'Industry', type: 'status', options: 'industry', width: W.status },
      { id: 'status', label: 'Status', type: 'status', options: 'clientStatus', width: W.status },
      { id: 'health', label: 'Health', type: 'status', options: 'health', width: W.status },
      { id: 'account_manager_id', label: 'Account manager', type: 'person', width: W.person },
      { id: 'arr', label: 'Annual value', type: 'money', width: W.money },
      { id: 'since', label: 'Client since', type: 'date', width: W.date },
      { id: 'region', label: 'Region', type: 'text', width: 130 },
      { id: 'nps', label: 'Last NPS', type: 'num', width: W.num },
    ],
  },
  contacts: {
    title: 'Contacts',
    blurb: 'The people on the client side — who to call, and when they were last spoken to.',
    newFields: ['name','client_id','title','email','owner_id'],
    views: ['table'], groupBy: 'client_id',
    columns: [
      { id: 'name', label: 'Contact', type: 'text', width: W.name },
      { id: 'client_id', label: 'Account', type: 'ref', ref: 'clients', width: W.text },
      { id: 'title', label: 'Title', type: 'text', width: 180 },
      { id: 'email', label: 'Email', type: 'text', width: 220 },
      { id: 'phone', label: 'Phone', type: 'text', width: 150 },
      { id: 'is_decision_maker', label: 'Decision maker', type: 'bool', width: 130 },
      { id: 'last_touch', label: 'Last contact', type: 'date', width: 130 },
      { id: 'owner_id', label: 'Owned by', type: 'person', width: W.person },
    ],
  },
  proposals: {
    title: 'Proposals & quotes',
    blurb: 'What has gone out, what is being reviewed, and what has been signed.',
    newFields: ['name','client_id','status','amount','owner_id'],
    views: ['table', 'kanban'], groupBy: 'status', kanbanBy: 'status', cardColor: 'status',
    columns: [
      { id: 'name', label: 'Proposal', type: 'text', width: 320 },
      { id: 'client_id', label: 'Account', type: 'ref', ref: 'clients', width: W.text },
      { id: 'status', label: 'Status', type: 'status', options: 'proposalStatus', width: W.status },
      { id: 'amount', label: 'Amount', type: 'money', width: W.money },
      { id: 'owner_id', label: 'Prepared by', type: 'person', width: W.person },
      { id: 'sent_on', label: 'Sent', type: 'date', width: W.date },
      { id: 'valid_until', label: 'Valid until', type: 'date', width: W.date },
      { id: 'version', label: 'Rev', type: 'text', width: 70 },
    ],
  },
  invoices: {
    title: 'Invoices',
    blurb: 'Billing against signed work, and what is overdue.',
    newFields: ['number','client_id','project_id','status','amount','issued_on','due_on'],
    views: ['table'], groupBy: 'status',
    columns: [
      { id: 'number', label: 'Invoice', type: 'text', width: 180 },
      { id: 'client_id', label: 'Account', type: 'ref', ref: 'clients', width: W.text },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 200 },
      { id: 'status', label: 'Status', type: 'status', options: 'invoiceStatus', width: W.status },
      { id: 'amount', label: 'Amount', type: 'money', width: W.money },
      { id: 'issued_on', label: 'Issued', type: 'date', width: W.date },
      { id: 'due_on', label: 'Due', type: 'date', width: W.date },
    ],
  },
  projects: {
    title: 'Projects',
    blurb: 'Every engagement in flight, its phase, budget burn and delivery health.',
    newFields: ['name','client_id','status','health','lead_id','start_on','end_on','budget'],
    views: ['table', 'kanban', 'timeline', 'chart'], groupBy: 'status', kanbanBy: 'status', cardColor: 'health',
    timeline: { start: 'start_on', end: 'end_on', color: 'status', options: 'projectStatus' },
    columns: [
      { id: 'name', label: 'Project', type: 'text', width: 280 },
      { id: 'client_id', label: 'Account', type: 'ref', ref: 'clients', width: W.text },
      { id: 'status', label: 'Phase', type: 'status', options: 'projectStatus', width: W.status },
      { id: 'health', label: 'Health', type: 'status', options: 'health', width: 120 },
      { id: 'lead_id', label: 'Delivery lead', type: 'person', width: W.person },
      { id: 'timeline', label: 'Timeline', type: 'timeline', start: 'start_on', end: 'end_on', width: 210 },
      { id: 'platforms', label: 'Platforms', type: 'tags', width: W.timeline },
      { id: 'budget', label: 'Budget', type: 'money', width: W.money },
      { id: 'burned', label: 'Burned', type: 'money', width: W.money },
    ],
  },
  sprints: {
    title: 'Sprints',
    blurb: 'Two-week cycles per project, with commitment against what actually shipped.',
    newFields: ['name','project_id','status','goal','start_on','end_on','committed_points','scrum_master_id'],
    views: ['table', 'timeline', 'chart'], groupBy: 'project_id',
    timeline: { start: 'start_on', end: 'end_on', color: 'status', options: 'sprintStatus' },
    columns: [
      { id: 'name', label: 'Sprint', type: 'text', width: 230 },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 220 },
      { id: 'status', label: 'Status', type: 'status', options: 'sprintStatus', width: W.status },
      { id: 'goal', label: 'Sprint goal', type: 'text', width: 320 },
      { id: 'timeline', label: 'Dates', type: 'timeline', start: 'start_on', end: 'end_on', width: 200 },
      { id: 'committed_points', label: 'Committed', type: 'points', width: 100 },
      { id: 'completed_points', label: 'Completed', type: 'points', width: 100 },
      { id: 'scope_added_points', label: 'Scope added', type: 'points', width: 110 },
      { id: 'scrum_master_id', label: 'Scrum master', type: 'person', width: W.person },
    ],
  },
  tasks: {
    title: 'Sprint board',
    blurb: 'Every ticket across every squad — what stage it is in, who owns it, and what it is blocking.',
    newFields: ['title','project_id','sprint_id','department','status','assignee_id','priority','type','points','start_on','due_on','estimate_hours'],
    views: ['table', 'kanban', 'timeline', 'chart'], groupBy: 'sprint_id', kanbanBy: 'status', cardColor: 'priority',
    keyField: 'key', comments: true, subtasks: true,
    timeline: { start: 'start_on', end: 'due_on', color: 'status', options: 'taskStatus' },
    columns: [
      { id: 'title', label: 'Ticket', type: 'text', width: 340 },
      { id: 'status', label: 'Status', type: 'status', options: 'taskStatus', width: W.status },
      { id: 'assignee_id', label: 'Owner', type: 'person', width: W.person },
      { id: 'department', label: 'Squad', type: 'dept', width: 130 },
      { id: 'priority', label: 'Priority', type: 'status', options: 'priority', width: 120 },
      { id: 'type', label: 'Type', type: 'status', options: 'taskType', width: 120 },
      { id: 'points', label: 'Pts', type: 'points', width: W.points },
      { id: 'timeline', label: 'Timeline', type: 'timeline', start: 'start_on', end: 'due_on', width: W.timeline },
      { id: 'estimate_hours', label: 'Est. h', type: 'hours', width: 85 },
      { id: 'logged_hours', label: 'Logged h', type: 'hours', width: 95 },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 200 },
      { id: 'sprint_id', label: 'Sprint', type: 'ref', ref: 'sprints', width: 190 },
      { id: 'blocks', label: 'Blocks', type: 'text', width: 130 },
    ],
  },
  milestones: {
    title: 'Milestones',
    blurb: 'The dates clients actually feel. Flagged when they are at risk.',
    newFields: ['name','project_id','status','due_on','owner_id','note'],
    views: ['table', 'timeline'], groupBy: 'project_id', comments: true,
    timeline: { start: 'due_on', end: 'due_on', color: 'status', options: 'milestoneStatus', diamond: true },
    columns: [
      { id: 'name', label: 'Milestone', type: 'text', width: 300 },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 220 },
      { id: 'status', label: 'Status', type: 'status', options: 'milestoneStatus', width: W.status },
      { id: 'due_on', label: 'Target date', type: 'date', width: 130 },
      { id: 'owner_id', label: 'Owner', type: 'person', width: W.person },
      { id: 'client_visible', label: 'Client visible', type: 'bool', width: 130 },
      { id: 'note', label: 'Definition of done', type: 'text', width: 340 },
    ],
  },
  people: {
    title: 'Team directory',
    blurb: 'Every role at Nuuke, which squad they sit in, and how loaded they are.',
    newFields: ['name','role_title','department','seniority','status','capacity_hours','location','email'],
    views: ['table', 'kanban'], groupBy: 'department', kanbanBy: 'department', cardColor: 'department',
    columns: [
      { id: 'name', label: 'Name', type: 'text', width: 220 },
      { id: 'role_title', label: 'Position', type: 'text', width: 210 },
      { id: 'department', label: 'Squad', type: 'dept', width: 130 },
      { id: 'seniority', label: 'Level', type: 'status', options: 'seniority', width: 120 },
      { id: 'status', label: 'Status', type: 'status', options: 'peopleStatus', width: 130 },
      { id: 'capacity_hours', label: 'Capacity h/wk', type: 'hours', width: 130 },
      { id: 'location', label: 'Location', type: 'text', width: 140 },
      { id: 'email', label: 'Email', type: 'text', width: 230 },
      { id: 'started_on', label: 'Joined', type: 'date', width: W.date },
    ],
  },
  time_logs: {
    title: 'Time tracking',
    blurb: 'Hours logged against tickets, split billable and internal.',
    newFields: ['note','person_id','project_id','department','logged_on','hours'],
    views: ['table', 'chart'], groupBy: 'person_id',
    columns: [
      { id: 'note', label: 'Entry', type: 'text', width: 300 },
      { id: 'person_id', label: 'Who', type: 'person', width: W.person },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 210 },
      { id: 'logged_on', label: 'Date', type: 'date', width: W.date },
      { id: 'hours', label: 'Hours', type: 'hours', width: 90 },
      { id: 'billable', label: 'Billable', type: 'bool', width: 100 },
      { id: 'department', label: 'Squad', type: 'dept', width: 130 },
    ],
  },
  leave_requests: {
    title: 'Leave & availability',
    blurb: 'Who is away, when, and whether it clashes with a sprint.',
    newFields: ['title','person_id','type','status','start_on','end_on','days','cover_id'],
    views: ['table', 'timeline'], groupBy: 'status',
    timeline: { start: 'start_on', end: 'end_on', color: 'type', options: 'leaveType' },
    columns: [
      { id: 'title', label: 'Request', type: 'text', width: 230 },
      { id: 'person_id', label: 'Who', type: 'person', width: W.person },
      { id: 'type', label: 'Type', type: 'status', options: 'leaveType', width: W.status },
      { id: 'status', label: 'Status', type: 'status', options: 'leaveStatus', width: W.status },
      { id: 'timeline', label: 'Dates', type: 'timeline', start: 'start_on', end: 'end_on', width: 200 },
      { id: 'days', label: 'Days', type: 'num', width: 80 },
      { id: 'cover_id', label: 'Cover', type: 'person', width: W.person },
    ],
  },
  bugs: {
    title: 'Bug tracker',
    blurb: 'Defects by severity and platform, from report through to verification.',
    newFields: ['title','project_id','severity','status','platform','assignee_id','reporter_id','department'],
    views: ['table', 'kanban', 'chart'], groupBy: 'severity', kanbanBy: 'status', cardColor: 'severity',
    keyField: 'key', comments: true,
    columns: [
      { id: 'title', label: 'Defect', type: 'text', width: 340 },
      { id: 'severity', label: 'Severity', type: 'status', options: 'severity', width: W.status },
      { id: 'status', label: 'Status', type: 'status', options: 'bugStatus', width: W.status },
      { id: 'platform', label: 'Platform', type: 'status', options: 'platform', width: 140 },
      { id: 'assignee_id', label: 'Owner', type: 'person', width: W.person },
      { id: 'reporter_id', label: 'Reported by', type: 'person', width: W.person },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 200 },
      { id: 'found_in', label: 'Found in build', type: 'text', width: 140 },
      { id: 'reported_on', label: 'Reported', type: 'date', width: W.date },
      { id: 'department', label: 'Squad', type: 'dept', width: 130 },
    ],
  },
  test_runs: {
    title: 'QA test runs',
    blurb: 'Regression and release passes, with the case counts behind each verdict.',
    newFields: ['name','project_id','status','platform','owner_id','cases','run_on'],
    views: ['table', 'chart'], groupBy: 'status',
    columns: [
      { id: 'name', label: 'Test run', type: 'text', width: 300 },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 210 },
      { id: 'status', label: 'Result', type: 'status', options: 'testStatus', width: W.status },
      { id: 'platform', label: 'Platform', type: 'status', options: 'platform', width: 140 },
      { id: 'owner_id', label: 'QA owner', type: 'person', width: W.person },
      { id: 'cases', label: 'Cases', type: 'num', width: 85 },
      { id: 'passed', label: 'Passed', type: 'num', width: 85 },
      { id: 'failed', label: 'Failed', type: 'num', width: 85 },
      { id: 'coverage', label: 'Coverage', type: 'pct', width: 140 },
      { id: 'run_on', label: 'Run date', type: 'date', width: W.date },
    ],
  },
  releases: {
    title: 'Releases & store',
    blurb: 'Builds on their way to production, including app store review state.',
    newFields: ['name','project_id','status','platform','build','owner_id','target_on'],
    views: ['table', 'kanban', 'timeline'], groupBy: 'project_id', kanbanBy: 'status', cardColor: 'platform',
    comments: true,
    timeline: { start: 'code_freeze_on', end: 'target_on', color: 'status', options: 'releaseStatus' },
    columns: [
      { id: 'name', label: 'Release', type: 'text', width: 230 },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 210 },
      { id: 'status', label: 'Stage', type: 'status', options: 'releaseStatus', width: W.status },
      { id: 'platform', label: 'Platform', type: 'status', options: 'platform', width: 150 },
      { id: 'build', label: 'Build', type: 'text', width: 110 },
      { id: 'owner_id', label: 'Release manager', type: 'person', width: W.person },
      { id: 'timeline', label: 'Freeze → ship', type: 'timeline', start: 'code_freeze_on', end: 'target_on', width: 200 },
      { id: 'target_on', label: 'Target date', type: 'date', width: W.date },
      { id: 'notes', label: 'Release note', type: 'text', width: 300 },
    ],
  },
  tickets: {
    title: 'Client support',
    blurb: 'Inbound requests from live clients, tracked against the SLA in their contract.',
    newFields: ['subject','client_id','status','priority','assignee_id','channel'],
    views: ['table', 'kanban', 'chart'], groupBy: 'status', kanbanBy: 'status', cardColor: 'priority',
    keyField: 'key', comments: true,
    columns: [
      { id: 'subject', label: 'Request', type: 'text', width: 330 },
      { id: 'client_id', label: 'Account', type: 'ref', ref: 'clients', width: W.text },
      { id: 'status', label: 'Status', type: 'status', options: 'ticketStatus', width: W.status },
      { id: 'priority', label: 'Priority', type: 'status', options: 'priority', width: 120 },
      { id: 'assignee_id', label: 'Owner', type: 'person', width: W.person },
      { id: 'channel', label: 'Channel', type: 'status', options: 'channel', width: 120 },
      { id: 'sla_due_at', label: 'SLA', type: 'sla', width: 130 },
      { id: 'opened_on', label: 'Opened', type: 'date', width: W.date },
      { id: 'first_reply', label: 'First reply', type: 'text', width: 120 },
      { id: 'csat', label: 'CSAT', type: 'rating', width: 120 },
    ],
  },
  approvals: {
    title: 'Client approvals',
    blurb: 'Work handed to the client for sign-off. These are what the portal surfaces.',
    newFields: ['name','project_id','status','owner_id','due_on','note'],
    views: ['table', 'kanban'], groupBy: 'status', kanbanBy: 'status', cardColor: 'status', comments: true,
    columns: [
      { id: 'name', label: 'Deliverable', type: 'text', width: 320 },
      { id: 'project_id', label: 'Project', type: 'ref', ref: 'projects', width: 210 },
      { id: 'status', label: 'Status', type: 'status', options: 'approvalStatus', width: 170 },
      { id: 'owner_id', label: 'Sent by', type: 'person', width: W.person },
      { id: 'sent_on', label: 'Sent', type: 'date', width: W.date },
      { id: 'due_on', label: 'Needed by', type: 'date', width: 130 },
      { id: 'note', label: 'What we need', type: 'text', width: 320 },
    ],
  },
};

export const boardNames = Object.keys(BOARDS);
export const nameColumn = (board) => board.columns[0];
